name: CI

on:
  pull_request:
    paths-ignore:
      - "**"
      - "!.github/workflows/ci.ya?ml"
      - "!**.ino"

  push:
    paths-ignore:
      - "**"
      - "!.github/workflows/ci.ya?ml"
      - "!**.ino"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint sketches
        uses: arduino/arduino-lint-action@v1
        with:
          path: sketch

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          cli-version: "latest"
          fqbn: "arduino:avr:nano"
          sketch-paths: sketch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-warnings-report: true
