name: Lint

on:
  pull_request:
    paths-ignore:
      - "**"
      - "!.github/workflows/lint.ya?ml"
      - "!**.ino"
      - "!**.cpp"

  push:
    paths-ignore:
      - "**"
      - "!.github/workflows/lint.ya?ml"
      - "!**.ino"
      - "!**.cpp"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rename .cpp to .ino
        run: |
          for file in $(find . -name "*.cpp"); do
            mv "$file" "${file%.cpp}.ino"
          done

      - uses: arduino/arduino-lint-action@v1
        with:
          path: src
