name: Lint

on:
  pull_request:
    paths-ignore:
      - "**"
      - "!.github/workflows/lint.ya?ml"
      - "!**.ino"
      - "!**.cpp"

  push:
    paths-ignore:
      - "**"
      - "!.github/workflows/lint.ya?ml"
      - "!**.ino"
      - "!**.cpp"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          path: src
