name: Lint

on:
  pull_request:
    paths-ignore:
      - "**"
      - "!.github/workflows/lint.ya?ml"
      - "!**.ino"

  push:
    paths-ignore:
      - "**"
      - "!.github/workflows/lint.ya?ml"
      - "!**.ino"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint sketches
        uses: arduino/arduino-lint-action@v1
        with:
          path: sketch
